SenzaInfo:
  StackName: go-server
  Parameters:
  - Domain:
      Description: Domain to setup for this go-server.
  - SSLCertificateId:
      Description: The SSL certificate to use on the load balancer.
  - DockerImage:
      Description: go-server Docker image to use.
  - AvailabilityZone:
      Description: The availability zone in which the date EBS is created.
  - InstanceType:
      Description: AWS instance type of your go-server.

SenzaComponents:
- Configuration:
    Type: Senza::StupsAutoConfiguration

Resources:
  GoServerAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
      - "{{Arguments.AvailabilityZone}}"
      LaunchConfigurationName:
        Ref: "GoServerLaunchConfig"
      MinSize: 1
      MaxSize: 1
      LoadBalancerNames:
      - Ref: "GoServerLoadBalancer"
      CreationPolicy:
        ResourceSignal:
          Timeout: "PT15M"
          Count: "1"

  GoServerLaunchConfig:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      UserData:
        "Fn::Base64": "
runtime: Docker
source: '{{Arguments.DockerImage}}'
ports:
  8153: 8153
volumes:
  ebs:
    /dev/sdf: go-server-volume
mounts:
  /var/lib/go-server:
    partition: /dev/sdf
    erase_on_boot: false
"
      InstanceType: "{{Arguments.InstanceType}}"
      SecurityGroups:
      - Ref: "GoServerSecurityGroup"
      IamInstanceProfile:
        Ref: "GoServerInstanceProfile"

  GoServerLoadBalancer:
    Type: "AWS::ElasticLoadBalancing::LoadBalancer"
    Properties:
      LoadBalancerName: "GoServerLoadBalancer"
      AvailabilityZones:
      - "{{Arguments.AvailabilityZone}}"
      Listeners:
      - LoadBalancerPort: "443"
        InstancePort": "8153"
        Protocol": "HTTPS"
        SSLCertificateId: "{{Arguments.SSLCertificateId}}"
      SecurityGroups:
      - Ref: "GoLoadBalancerSecurityGroup"

  GoLoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: go-server load balancer security group
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0

  GoServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: go-server security group
      SecurityGroupIngress:
      # for debugging via piu
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      # HTTP from load balancer
      - IpProtocol: tcp
        FromPort: 8153
        ToPort: 8153
        SourceSecurityGroupId:
          Ref: GoLoadBalancerSecurityGroup

  GoServerInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
      - Ref: "GoServerRole"

  GoServerRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: AttachingEBS
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action: ec2:AttachVolume
            # TODO find a way to be very specific to the one EBS here
            Resource: "*"
          - Effect: Allow
            Action: ec2:DescribeVolumes
            Resource: "*"

